fix: Flaky test
Often fails with

		--- FAIL: TestPickNameWithDefault (0.05s)
		    survey_test.go:31: Select nothing, hence default
		    survey_test.go:31: Select first element
		    survey_test.go:31: Select Second element
		    survey_test.go:31: Select Last element
		    survey_test.go:76: Unexpected output.
		        Expected:
		        ? Pick third ;
		        Found:
		        ? Pick  [Use arrows to move, type to filter]
		        ? Pick third